//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudokuSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudokuSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 8 0 2 0 9 1 0 4 5 6 0 0 4 0 0 7 0 0 1 2 0 3 5 9 0 0 2 0 5 6 9 7 8 0 0 9 7 0 4 0 1 0 0 3 6 4 0 0 8 0 0 0 5 0 0 3 8 0 0 5 6 0 7 9 0 0 2 3 0 1 8 0 0 4 0 1 0 2 3 7
        ///2 8 6 0 5 1 9 0 0 9 7 3 0 4 0 0 0 6 1 0 0 0 7 9 3 2 0 0 6 0 4 9 2 0 1 0 5 9 7 8 1 6 0 0 4 0 0 2 7 0 5 0 8 0 8 3 0 1 0 0 0 9 0 0 0 1 0 0 4 5 6 3 0 4 0 5 2 0 8 7 0
        ///0 0 6 0 3 0 9 4 7 3 0 5 4 0 0 2 0 0 0 2 0 8 9 1 0 0 6 8 0 0 1 2 0 7 6 0 0 0 1 0 4 0 3 9 5 6 4 9 7 0 0 0 0 8 7 0 0 0 0 0 8 0 9 5 3 0 0 6 7 0 1 2 0 1 4 2 0 5 0 0 3
        ///0 7 3 0 0 5 2 0 0 8 4 6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GridEasy {
            get {
                return ResourceManager.GetString("GridEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 8 0 2 0 0 1 0 0 0 0 0 0 0 0 0 7 0 4 0 0 0 0 5 9 0 0 0 3 0 0 9 7 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 8 0 0 0 5 1 0 0 0 0 4 0 6 0 0 9 0 0 0 3 0 0 8 0 5 0 0 0 6 2 3 7
        ///0 8 6 3 5 0 9 0 0 0 0 0 0 0 0 1 0 0 0 5 0 0 7 0 3 0 0 3 0 0 0 9 0 0 0 0 0 0 7 0 0 6 0 0 4 4 1 2 0 0 0 0 8 0 0 3 0 0 0 0 0 0 0 7 0 0 0 8 0 0 0 0 0 0 0 5 0 0 0 0 0
        ///0 8 6 0 0 0 0 4 0 0 0 0 0 7 0 2 0 0 0 0 7 0 0 1 5 3 0 0 0 3 0 0 0 7 6 0 2 0 0 6 4 0 0 0 5 0 0 9 0 0 0 1 0 8 0 0 0 0 0 0 0 0 0 0 0 0 9 6 0 0 0 0 0 1 0 0 0 5 0 0 0
        ///1 7 0 0 0 0 0 0 0 8 0 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GridEvil {
            get {
                return ResourceManager.GetString("GridEvil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 8 7 0 6 9 0 0 4 5 0 0 1 0 0 0 0 2 0 0 0 7 3 0 0 0 6 2 3 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8 0 0 0 5 1 0 0 0 0 0 0 0 0 0 9 6 5 0 0 0 1 0 0 0 4 0 0 0 2 3 7
        ///2 0 0 0 0 0 9 0 7 9 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 6 0 0 9 0 0 1 0 0 0 0 8 0 0 2 3 4 0 0 0 0 3 5 0 8 0 0 3 5 0 0 7 0 0 0 0 0 1 0 0 4 0 6 0 0 0 9 0 2 0 8 0 0
        ///0 0 6 0 3 0 0 0 0 0 0 0 0 0 0 2 8 1 0 0 7 0 0 0 5 0 0 8 5 0 0 0 0 7 6 0 0 0 0 0 4 0 0 9 0 0 4 0 0 5 3 0 0 0 7 0 0 0 0 0 8 0 0 0 0 0 9 6 0 0 1 0 0 0 0 2 0 0 0 0 0
        ///1 0 0 0 0 5 2 9 0 0 0 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GridHard {
            get {
                return ResourceManager.GetString("GridHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0 7 2 0 9 0 5 0 0 6 0 0 0 0 3 0 0 4 1 0 7 0 0 0 8 6 2 3 5 6 0 7 0 0 1 0 7 0 4 5 0 0 2 0 0 0 1 0 8 0 0 9 0 0 0 0 0 0 0 0 6 0 0 0 0 0 0 3 4 0 0 8 5 0 0 1 0 0 0 7
        ///0 8 6 0 0 0 0 4 7 9 7 3 0 0 0 0 5 0 1 0 0 0 0 0 0 0 0 3 0 8 0 9 0 0 0 0 5 0 0 0 1 6 2 0 4 0 1 2 7 3 0 6 0 0 0 0 5 0 6 0 0 9 0 0 2 0 0 0 4 0 0 3 0 4 0 5 0 0 8 7 1
        ///0 8 0 0 0 0 0 0 7 3 0 5 4 0 6 2 0 0 0 2 0 0 9 1 0 0 6 8 0 0 0 2 9 7 6 0 0 0 1 0 0 0 0 9 5 6 4 0 0 5 3 0 0 0 7 6 0 3 0 0 8 0 0 0 3 0 0 0 0 4 1 2 9 0 4 2 0 5 0 0 0
        ///1 7 0 0 4 0 0 0 6 8 4 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GridMedium {
            get {
                return ResourceManager.GetString("GridMedium", resourceCulture);
            }
        }
    }
}
